package org.drools.examples
 
import org.drools.examples.Message;
 
rule "Hello World P1"
	when
		m : Message( status == Message.HELLO, myMessage : message )
	then
		System.out.println( myMessage ); 
		m.setMessage( "Goodbye cruel world" );
		m.setStatus( Message.GOODBYE );
		update( m );
end

rule "GoodBye P1"
	when
		Message( status == Message.GOODBYE, myMessage : message )
	then
		System.out.println( myMessage );
end